FROM node:12.22-buster
MAINTAINER "János Gats <gatsjanos@gmail.com>"

EXPOSE 3000
EXPOSE 9229
ENV APP_HOME=/app

RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

COPY ./package.json ${APP_HOME}/
COPY ./package-lock.json ${APP_HOME}/
RUN npm install && npx next telemetry disable

COPY . ${APP_HOME}/.

ENTRYPOINT ["sh"]
CMD ["-c", "npm run dev" ]
